{{- range .Values.domains -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-{{ .names.common_name }}
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
spec:
  privateKey:
    algorithm: RSA
    size: 4096
  secretName: certbot-{{ .names.common_name }}
  dnsNames: 
    - {{ .names.common_name }} 
{{if .names.subject_alternative_names -}}
{{ toYaml .names.subject_alternative_names | indent 4 }}
{{- end}}
  issuerRef:
    name: {{ if .letsencrypt_prod -}}  "letsencrypt-prod" {{- else -}} "letsencrypt-staging" {{- end }}
    kind: Issuer
    group: cert-manager.io
---
{{- end}}
