kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ingress
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets","services"]
  verbs: ["get", "list", "watch"]
