{{- range .Values.domains -}}
{{- if .robots -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: robots-{{ .names.common_name }}
data:
  robots.txt: |
    {{- range .robots.entries }}
    User-agent: {{ .user_agent }}
    {{- range .allow }}
    Allow: {{.}}
    {{- end }}
    {{- range .disallow }}
    Disallow: {{.}}

    {{ end }}
    {{ end }}
    {{- range .robots.sitemap }}
    Sitemap: {{ . }} 
    {{- end }}
---
{{- end }}
{{- end }}
