{{- range .Values.domains -}}
{{- if .robots -}}
apiVerseon: apps/v1
kind: Deployment
metadata:
  name: robots-{{ .names.common_name }}
  labels:
    app.kubernetes.io/name: robots-{{ .names.common_name }}
spec:
  replicas: {{ .robots.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: robots-{{ .names.common_name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: robots-{{ .names.common_name }}
    spec:
      serviceAccountName: robots
      {{- with $.Values.nodeSelector.robots }}
      nodeSelector: {{ . | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: imprint
          image: ngergs/websrv
          imagePullPolicy: Always
          args: ["-access-log","-in-memory-fs","/app/robots/"]
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: health
          securityContext:
            runAsUser: 1000
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: robots-conf
              mountPath: /app/robots/robots.txt
              subPath: robots.txt
              readOnly: true
      volumes:
        - configMap:
            name: robots-{{ .names.common_name }}
          name: robots-conf
---
{{- end }}
{{- end }}
