apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress
  labels:
    app.kubernetes.io/name: ingress
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingress
    spec:
      serviceAccountName: ingress
      nodeSelector:
        cloud.google.com/gke-nodepool: homepage-ngergs-gke-ingress-node-pool
      containers:
        - name: ingress
          image: ngergs/ingress
          imagePullPolicy: Always
          args:
            - "-access-log"
            - "-hsts"
            - "-hsts-subdomains"
            - "-hsts-preload"
            - "-hsts-max-age"
            - "63072000"
            - "-ingress-class-name"
            - {{.Values.ingressClassName}}
            - "-read-timeout"
            - "300"
            - "-write-timeout"
            - "300"
          securityContext:
            runAsUser: 1000
            readOnlyRootFilesystem: true
          ports:
            - name: https
              containerPort: 8443
              hostPort: 443
              protocol: TCP
            - name: http
              containerPort: 8080
              hostPort: 80
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet: 
              path: /health
              port: health
