{{- range .Values.domains -}}
{{- if .robots -}}
apiVersion: v1
kind: Service
metadata:
  name: robots-{{ .names.common_name | replace "." "-" }}
  labels:
    app.kubernetes.io/name: robots-{{ .names.common_name }}
spec:
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: robots-{{ .names.common_name }}
---
{{- end }}
{{- end }}
