name: release

env:
  go-version: '^1.19.2'

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-and-pre-release:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        uses: ngergs/composite-actions/go-test@main
        with:
          go-version: ${{ env.go-version }}
      - name: Determine release
        uses:  ngergs/composite-actions/prepare-semantic-release@main
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-emojis: true
    outputs:
      version: ${{ steps.semrel.outputs.version }}
      release-notes-cache-key: ${{ steps.semrel.outputs.release-notes-cache-key }}
  release-docker:
    needs: test-and-pre-release
    if: needs.test-and-pre-release.outputs.version != ''
    runs-on: ubuntu-latest
    steps:
      - name: Release docker
        uses: ngergs/composite-actions/release-docker@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          docker-image-name: ingress
          dockerhub-username:  ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}
          release-version: ${{ needs.test-and-pre-release.outputs.version }}
          release-notes-cache-key: ${{ needs.test-and-pre-release.outputs.release-notes-cache-key }}
          dockerfile: build/Dockerfile
