name: test

env:
  go-version: '^1.21.3'

on:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        uses: ngergs/composite-actions/go-test@main
        with:
          go-version: ${{ env.go-version }}
